#!/usr/bin/bash

# Show log (last first)
# 
# Log line format::
#
#   2021-08-15T02:56:10+0700  #=<event> <data> ...   (from C: strftime:%FT%T%z)
#   2021-08-15T02:56:14+07:00 #=<event> <data> ...   (from unix: date --iso==s)
#
#   (the format is compatible with
#    inline metadata of ANSI files)
#
# Examples:
#   #=W <URL>
#   #=WDISPLAY <URL> <first> <lines>


# Usage:
#   ./wlog [lines]

# get lines
stty size >/dev/null

# show log entries in reverse order

tac .wlog | tail -${1:-$((LINES-3))}

