#!/usr/bin/bash

# quote a string to be safe filename
#
# WARNING: has to be in sync with
#    ./jio.c:dstrncaturi()!
#
# basically all "offensive" non A-Z or converted to '%xx' using URL quoting

# !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~

# ; , =reserved in html

echo "$*" | perl -e "\$_=<>;s/([ -\-\\/,:;<>\\?\@\\[\\\\\\]\\^\\'\\{\\|\\}\\~\`~])/sprintf('%%%02x', ord(\$1))/eg;print;"



